# 9) Compute the FFT of a given signal with N = 8 using Radix-2 algorithm.

In [1]:
import numpy as np
def Radix2_FFT(f, n=None, fixed=False):
    N = len(f)
    # this fixed boolean is for fixed 8 point DFT as the question no matter what's the input signal's length
    if fixed:
        f = f[:8]
        N = 8
        fixed = False
        
    # this if condition is for user's N input
    if n != None:
        N = n
        f = np.concatenate([f, [0]*(N-len(f))])
    if N<=1:
        return f
    
    even = Radix2_FFT(f[0::2])
    odd = Radix2_FFT(f[1::2])
    
    fft = np.zeros(N).astype(np.complex64)
    
    for i in range(N//2):
        fft[i] = even[i] + np.exp((-2j*np.pi*i)/N) * odd[i]
        fft[i + N//2] = even[i] - np.exp((-2j*np.pi*i)/N) * odd[i]
        
    return fft

In [2]:
# Here by default FFT performs according to the length of the signal
x = [0,1,2,3,4,5,6,7]
fft = Radix2_FFT(x)
print(fft)

[28.+0.j        -4.+9.656855j  -4.+4.j        -4.+1.6568543j
 -4.+0.j        -4.-1.6568543j -4.-4.j        -4.-9.656855j ]


In [3]:
# Fixed to 8 point FFT
fft2 = Radix2_FFT(x, fixed = True)
print('FFT of a given signal with N = 8 using Radix-2 algorithm : {}'.format(fft2))

FFT of a given signal with N = 8 using Radix-2 algorithm : [28.+0.j        -4.+9.656855j  -4.+4.j        -4.+1.6568543j
 -4.+0.j        -4.-1.6568543j -4.-4.j        -4.-9.656855j ]


In [4]:
# User's N input N point FFT(N should be 2's power)
fft3 = Radix2_FFT(x, n = 16)
print(fft3)

[28.        +0.j        -9.137071 -20.109358j  -4.        +9.656855j
  2.3800855 -5.986423j  -4.        +4.j         3.2767687 -2.6727145j
 -4.        +1.6568543j  3.480217  -0.7956491j -4.        +0.j
  3.480217  +0.7956491j -4.        -1.6568543j  3.2767687 +2.6727145j
 -4.        -4.j         2.3800855 +5.986423j  -4.        -9.656855j
 -9.137071 +20.109358j ]


# cross check

In [5]:
np.fft.fft(x)

array([28.+0.j        , -4.+9.65685425j, -4.+4.j        , -4.+1.65685425j,
       -4.+0.j        , -4.-1.65685425j, -4.-4.j        , -4.-9.65685425j])

In [6]:
np.fft.fft(x,8)

array([28.+0.j        , -4.+9.65685425j, -4.+4.j        , -4.+1.65685425j,
       -4.+0.j        , -4.-1.65685425j, -4.-4.j        , -4.-9.65685425j])

In [7]:
np.fft.fft(x,16)

array([28.         +0.j        , -9.13707118-20.10935797j,
       -4.         +9.65685425j,  2.3800856  -5.98642305j,
       -4.         +4.j        ,  3.27676865 -2.67271455j,
       -4.         +1.65685425j,  3.48021694 -0.79564947j,
       -4.         +0.j        ,  3.48021694 +0.79564947j,
       -4.         -1.65685425j,  3.27676865 +2.67271455j,
       -4.         -4.j        ,  2.3800856  +5.98642305j,
       -4.         -9.65685425j, -9.13707118+20.10935797j])

In [8]:
np.fft.ifft(fft)

array([0.        +0.j, 0.99999993+0.j, 1.99999991+0.j, 2.99999993+0.j,
       4.        +0.j, 5.00000007+0.j, 6.00000009+0.j, 7.00000007+0.j])